### ISSUE TITLE
Calling $sub again on a previously published message triggers the sub

### ISSUE THREAD

**Issue by thardy** [sqlProvider/angular2-pubsub#10]
We have a scenario where we publish a message, and a component that subscribes to that message in it's ngOnInit gets called like it's supposed to.  When that component get re-initialized, the $sub executes again, and the sub immediately gets triggered AGAIN, even though the publish happened in the past.  In fact, if we legitimately publish again, the next time the component's ngOnit subscribes to the message, it will get called TWICE.

It's like, every time we subscribe, we get the entire history of that message.  Are the messages kept in some sort of queue, and are they not being cleared out or something?  Do they need to be destroyed/handled, or they are doomed to be repeated over and over again?

**Comment by sqlProvider** [comment]
I'm sorry for the late reply @thardy.
Are you using ngOnDestroy? Like this.

```javascript
ngOnDestroy() {
  this.subber.unsubscribe();
}
```
