### ISSUE TITLE
Compilation Problem

### ISSUE THREAD

**Issue by queejie** [sqlProvider/angular2-pubsub#6]
I realize this may not be an issue for this module alone, because we came across it with another third-party module as well.  But I am hoping you might be able to help.  The error we get is shown below.  I tried installing with both the "next" option and without, with the same result.  We are using Angular 2.4.6.

``ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /Users/dqj/Local/dev/apps/pl3/pepe/frontend/node_modules/angular2-pubsub/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /Users/dqj/Local/dev/apps/pl3/pepe/frontend/node_modules/angular2-pubsub/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /Users/dqj/Local/dev/apps/pl3/pepe/frontend/node_modules/angular2-pubsub/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /Users/dqj/Local/dev/apps/pl3/pepe/frontend/node_modules/angular2-pubsub/node_modules/@angular/core/index.d.ts, resolving symbol PubSubModule in /Users/dqj/Local/dev/apps/pl3/pepe/frontend/node_modules/angular2-pubsub/esm/src/angular2-pubsub.module.d.ts, resolving symbol PubSubModule in /Users/dqj/Local/dev/apps/pl3/pepe/frontend/node_modules/angular2-pubsub/esm/src/angular2-pubsub.module.d.ts
webpack: Failed to compile.
``

**Comment by sqlProvider** [comment]
Do you get this error when you try AOT Compiling?

@queejie

**Comment by queejie** [comment]
Yes, that's when I get it.

**Comment by sqlProvider** [comment]
I use `angular-cli@latest` and `Angular@2.4.7`. AOT compiling finish with no error. Can you try [this].(https://github.com/angular/angular/issues/11262)

![AOT compiling log](http://i.imgur.com/0Bfg7iF.png)

**Comment by ghost** [comment]
I have the same problem. Does anyone have solved the issue?

<img width="434" alt="screen shot 2018-07-11 at 15 18 20" src="https://user-images.githubusercontent.com/2828010/42574671-a0caad78-8527-11e8-8a18-9c6ea8137f12.png">

**Comment by sqlProvider** [comment]
@pdmshrestha What is your Angular version?

**Comment by queejie** [comment]
FWIW, as the original poster, I no longer feel that I need this module.  I was using it because I didn't understand existing Angular subscription capability well enough.  Using a service to hold an EventEmitter, one can publish and subscribe using existing functionality.
