### ISSUE TITLE
Duplicate declaration of  'PubSubService' 

### ISSUE THREAD

**Issue by esakal** [sqlProvider/angular2-pubsub#7]
https://github.com/sqlProvider/angular2-pubsub/blob/586bca11f23f5d85135479e32f7bc373d0f9920b/src/angular2-pubsub.module.ts#L6

I think you need to remove the line above. Otherwise difference modules will have separated pubsub services. All you need is the one declared in the `forRoot()`

**Comment by sqlProvider** [comment]
Thx for report. I will check.
