### ISSUE TITLE
Angular 5.x.x | PubSubModule throws Unexpected value '[object Object]' 

### ISSUE THREAD

**Issue by polu3g** [sqlProvider/angular2-pubsub#9]
Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.

@NgModule({
  imports: [
      PubSubModule.forRoot()
],

for 
 "@angular/core": "5.0.0",  

works fine for 4.xx

Pls fix.. Thanks

**Comment by polu3g** [comment]
Fix like below: return type issues 👍 

> export interface IPubSubService {
> 	$pub(event: string, eventObject?: any): **void**

;

**Comment by sqlProvider** [comment]
Hi @polu3g thanks for report I will add this.
